global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'questionnaire-api'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['questionnaire.api:7141']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
