services:
  questionnaire.api:
    container_name: questionnaire.api
    image: ${DOCKER_REGISTRY-}questionnaire.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5008
      - ASPNETCORE_HTTPS_PORTS=7141
    ports:
      - 5008:5008
      - 7141:7141
    build:
      context: .
      dockerfile: Sample.Questionnaire.API/Dockerfile
    volumes:
      - ./logs:/logs/samples/questionnaire
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro

  mssql.db:
    container_name: mssql.db
    image: ${DOCKER_REGISTRY-}mssql.db
    environment:
      SA_PASSWORD: '#&E*ye76t&#YGet8q7#*&YTtw8qytt&E7t378ET78etW*87'
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
    build:
      context: ../../sample.mssql.sqlproj.template/Sample.Database
      dockerfile: Sample.Database/Dockerfile

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-data:/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro # Mount the proc directory from the host
      - /sys:/host/sys:ro # Mount the sys directory from the host
      - /:/rootfs:ro # Mount the root filesystem from the host
    command:
      - '--path.procfs=/host/proc' # Path to the procfs directory
      - '--path.rootfs=/rootfs' # Path to the root filesystem
      - '--path.sysfs=/host/sys' # Path to the sysfs directory
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' # Exclude certain filesystem mount points from collection
